/**
 * Arena Audit — GitHub Integration (P12-02, P12-04)
 *
 * Posts a Check Run and an idempotent PR comment. Payload builders are pure
 * and unit-tested; the API layer is a thin fetch wrapper over the fixed
 * api.github.com host (GITHUB_TOKEN with `checks: write` + `pull_requests: write`).
 *
 * Policy (P12 gate): conclusion is failure only for NEW verified high
 * findings or failing machine gates — known debt never blocks a PR.
 */

const API = 'https://api.github.com';
export const COMMENT_MARKER = '<!-- arena-audit:report -->';

/** Decide the check conclusion from audit results (pure). */
export function decideConclusion({ gates = [], findings = [], coverage = null }) {
  const failingGate = gates.some((g) => g.status === 'fail');
  const newVerifiedHigh = findings.some((f) => f.status === 'verified' && f.severity === 'high' && f.baselineState !== 'known');
  if (failingGate || newVerifiedHigh) return 'failure';
  if (coverage && coverage.percent === 0) return 'neutral'; // nothing could be checked — honest state
  return 'success';
}

/** Build the Check-Run request body (pure). */
export function buildCheckPayload({ conclusion, scores, coverage = null, newVerified, knownVerified, gates, runMeta }) {
  const gateLines = gates.map((g) => `- ${g.id}: **${g.status}**`).join('\n') || '- (no gates detected)';
  return {
    name: 'arena-audit',
    head_sha: runMeta?.commit || undefined,
    status: 'completed',
    conclusion,
    output: {
      title: `Arena Audit — ${scores?.overall ?? 'N/A'}/100 (coverage ${coverage?.percent ?? 0}%)`,
      summary: [
        `**Overall:** ${scores?.overall ?? 'N/A (insufficient evidence)'} / 100 · coverage ${coverage?.percent ?? 0}%`,
        '',
        '**Machine gates:**',
        gateLines,
        '',
        `**Findings:** ${newVerified} new · ${knownVerified} known (baseline)`,
        '',
        conclusion === 'failure'
          ? '❌ Blocking: failing gate(s) or new verified high-severity finding(s).'
          : conclusion === 'neutral'
            ? '⚠️ Nothing could be checked (no gates/coverage) — NOT a pass.'
            : '✅ No new blocking issues.',
      ].join('\n'),
    },
  };
}

/** Build the PR comment body (pure) — includes the marker for idempotent updates. */
export function buildPrComment({ runMeta, scores, coverage, gates, newFindings, knownCount, fixedCount, priorities }) {
  const lines = [
    COMMENT_MARKER,
    `## 🛡️ Arena Audit (${runMeta?.mode || 'full'})`,
    '',
    `**Overall:** ${scores?.overall ?? 'N/A'} / 100 · coverage ${coverage?.percent ?? 0}% · run \`${runMeta?.runId || 'n/a'}\``,
    '',
    `| ✅ New | 📌 Known | 🧹 Fixed vs baseline |`,
    `|---|---|---|`,
    `| ${newFindings.length} | ${knownCount} | ${fixedCount} |`,
    '',
    '**Gates:** ' + (gates.map((g) => `${g.id}:${g.status}`).join(' · ') || 'none detected'),
    '',
  ];
  if (newFindings.length > 0) {
    lines.push('### 🆕 New findings');
    for (const f of newFindings.slice(0, 10)) {
      lines.push(`- **[${f.severity}]** \`${f.path}\` — ${f.problem}${f.fingerprint ? ` · \`${String(f.fingerprint).slice(0, 8)}\`` : ''}`);
    }
  } else {
    lines.push('✅ **No new findings** beyond the accepted baseline.');
  }
  if (priorities?.length) {
    lines.push('', '### 🎯 Top priorities');
    priorities.slice(0, 5).forEach((p, i) => lines.push(`${i + 1}. \`${p.path || p.where}\` — ${p.what}`));
  }
  lines.push('', '_Generated by [arena-audit](https://github.com/ali39999-hue/arena-audit) — "NOT CHECKED ≠ PASS"_');
  return lines.join('\n');
}

// ---------------------------------------------------------------------------
// API layer (thin wrappers; token from env)
// ---------------------------------------------------------------------------

function headers(token) {
  return {
    'Authorization': `Bearer ${token}`,
    'Accept': 'application/vnd.github+json',
    'X-GitHub-Api-Version': '2022-11-28',
    'Content-Type': 'application/json',
    'User-Agent': 'arena-audit',
  };
}

export async function createCheckRun({ token, repo, payload }) {
  const resp = await fetch(`${API}/repos/${repo}/check-runs`, {
    method: 'POST', headers: headers(token), body: JSON.stringify(payload),
  });
  if (!resp.ok) throw new Error(`check-run failed: ${resp.status} ${(await resp.text()).slice(0, 200)}`);
  return resp.json();
}

export async function upsertPrComment({ token, repo, prNumber, body }) {
  const listResp = await fetch(`${API}/repos/${repo}/issues/${prNumber}/comments?per_page=100`, {
    headers: headers(token),
  });
  if (!listResp.ok) throw new Error(`comment list failed: ${listResp.status}`);
  const comments = await listResp.json();
  const existing = comments.find((c) => c.body?.includes(COMMENT_MARKER));
  if (existing) {
    const resp = await fetch(`${API}/repos/${repo}/issues/comments/${existing.id}`, {
      method: 'PATCH', headers: headers(token), body: JSON.stringify({ body }),
    });
    if (!resp.ok) throw new Error(`comment update failed: ${resp.status}`);
    return { updated: true, id: existing.id };
  }
  const resp = await fetch(`${API}/repos/${repo}/issues/${prNumber}/comments`, {
    method: 'POST', headers: headers(token), body: JSON.stringify({ body }),
  });
  if (!resp.ok) throw new Error(`comment create failed: ${resp.status}`);
  return { updated: false, id: (await resp.json()).id };
}

/** Extract PR number from Actions env (GITHUB_REF=refs/pull/123/merge). */
export function prNumberFromEnv(env = process.env) {
  const ref = env.GITHUB_REF || '';
  const m = ref.match(/refs\/pull\/(\d+)\//);
  return m ? parseInt(m[1], 10) : (env.GITHUB_PR_NUMBER ? parseInt(env.GITHUB_PR_NUMBER, 10) : null);
}
